"""
如果你想测试沪深股票 + ETF

建议你现在先把 config.py 改成：

INCLUDE_MARKETS = ("sh", "sz")

INCLUDE_INSTRUMENT_TYPES = (
    "stock",
    "etf_fund",
)

然后保持：

READ_LIMIT = 200

这样会读沪深市场的前 200 个股票/ETF，更适合测试。

如果你只想看 ETF 选股

可以改成：

INCLUDE_MARKETS = ("sh", "sz")

INCLUDE_INSTRUMENT_TYPES = (
    "etf_fund",
)

READ_LIMIT = 200

这样输出的 strategy_selection.parquet 里应该就是 ETF / 场内基金。


"""
# -*- coding: utf-8 -*-
from pathlib import Path

TDX_DIR = Path(r"F:\tongxinda")
PROJECT_DIR = Path(r"F:\通信达量化\tdx_modular_quant_project_v2_all_instruments")

DATA_DIR = PROJECT_DIR / "data"
RAW_EXTERNAL_DIR = DATA_DIR / "raw_external"
PROCESSED_DIR = DATA_DIR / "processed"
REPORT_DIR = DATA_DIR / "reports"
RESULT_DIR = PROJECT_DIR / "results"
RUNS_DIR = PROJECT_DIR / "runs"
PIPELINE_CACHE_JSON = REPORT_DIR / "pipeline_run_cache.json"

for folder in [DATA_DIR, RAW_EXTERNAL_DIR, PROCESSED_DIR, REPORT_DIR, RESULT_DIR, RUNS_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

START_DATE = "2018-01-01"
END_DATE = None

# V2: keep all beginner-accessible and useful market instruments.
# Types:
# stock, etf_fund, index, bond, convertible_bond, b_share, unknown
INCLUDE_MARKETS = ("sh", "sz", "bj")
INCLUDE_INSTRUMENT_TYPES = (
    "stock",
    "etf_fund",
    "index",
    "bond",
    "convertible_bond",
    "b_share",
    "unknown",
)

# First test with 50. Change to None for all. None

READ_LIMIT = None

ABNORMAL_RETURN_THRESHOLD = 0.20

ENABLE_HOT_THEME_BIAS = True
HOT_THEME_SLOT_RATIO = 0.3
HOT_THEME_WEIGHTS = {
    "ai_infrastructure": 1.00,
    "robotics_automation": 0.90,
    "low_altitude_aerospace": 0.80,
}

ENABLE_LEARNING_STRATEGIES = True
LEARNING_STRATEGY_WHITELIST = None
ENABLE_PLACEHOLDER_STRATEGIES = False
ENABLE_QUANTUM_INSPIRED_STRATEGIES = False

ENABLE_EXPERIMENT_TRACKING = True
RUN_ID_PREFIX = "run"
RUN_METADATA_FILENAME = "metadata.json"
DATA_VERSION = "tdx_daily_v2"
ADJUSTMENT_DATA_VERSION = "baostock_adjust_factor_v1"
CORPORATE_ACTION_DATA_VERSION = "baostock_dividend_v1"
RESEARCH_RUN_MODE = "exploratory"
FORMAL_MODE_NAME = "formal"
ADJUSTED_FEATURE_PRICE_MODE = "point_in_time_backward"
RESEARCH_IDEA_ID = "baseline_rebuild_v2"
RESEARCH_ATTEMPT_ID = "attempt_01"
BASELINE_VERSION = "pre_p0_legacy"
WALK_FORWARD_TRAIN_PERIODS = 252
WALK_FORWARD_VALIDATION_PERIODS = 63
WALK_FORWARD_TEST_PERIODS = 63
WALK_FORWARD_STEP_PERIODS = 21
WALK_FORWARD_PURGE_PERIODS = 5
WALK_FORWARD_EMBARGO_PERIODS = 5
VALIDATION_MAX_ATTEMPTS = 5
TEST_LOCK_ENABLED = True
LABEL_DEFAULT_HORIZONS = (5, 10, 20)
LABEL_DEFAULT_TARGET_RETURN = 0.02
FEATURE_WINSORIZE_LOWER = 0.01
FEATURE_WINSORIZE_UPPER = 0.99
FEATURE_ROBUST_SCALE_EPSILON = 1e-9
FACTOR_MIN_COVERAGE_RATIO = 0.10
FACTOR_REGISTRY_STATUS_DEFAULT = "experimental"
REPORT_OUTPUT_MD = RESULT_DIR / "strategy_diagnostic_report.md"
FEATURE_COVERAGE_REPORT_CSV = REPORT_DIR / "feature_coverage_report.csv"
FEATURE_DISTRIBUTION_REPORT_CSV = REPORT_DIR / "feature_distribution_report.csv"
FEATURE_STABILITY_REPORT_CSV = REPORT_DIR / "feature_stability_report.csv"
FEATURE_REGISTRY_REPORT_CSV = REPORT_DIR / "feature_registry_validation_report.csv"
EVENT_DATA_PARQUET = PROCESSED_DIR / "event_data.parquet"
EVENT_DATA_QUALITY_CSV = REPORT_DIR / "event_data_quality_report.csv"
QML_MIN_TEST_WINDOWS = 5
QML_WILCOXON_P_THRESHOLD = 0.05
QML_MAX_DRAWDOWN_MULTIPLIER = 1.2

DEFAULT_CORPORATE_ACTIONS_SOURCE = "manual_csv"
BAOSTOCK_ADJUSTMENT_SOURCE = "baostock_adjust_factor"
BAOSTOCK_CORPORATE_ACTION_SOURCE = "baostock_dividend"
CODE_MAPPING_CSV = REPORT_DIR / "code_mapping_report.csv"
CORPORATE_ACTIONS_PARQUET = PROCESSED_DIR / "corporate_actions.parquet"
CORPORATE_ACTIONS_QUALITY_CSV = REPORT_DIR / "corporate_actions_quality_report.csv"
ADJUSTMENT_FACTORS_PARQUET = PROCESSED_DIR / "adjustment_factors.parquet"
ADJUSTMENT_FACTORS_QUALITY_CSV = REPORT_DIR / "adjustment_factors_quality_report.csv"
MARKET_CAP_PARQUET = PROCESSED_DIR / "market_cap_history.parquet"
MARKET_CAP_QUALITY_CSV = REPORT_DIR / "market_cap_quality_report.csv"

COMMISSION_RATE = 0.0003
STAMP_DUTY_RATE = 0.001
SLIPPAGE_RATE = 0.0005
MIN_LOT_SIZE = 100
BACKTEST_INITIAL_CASH = 1_000_000.0
BACKTEST_RISK_FREE_RATE = 0.0
ENABLE_T_PLUS_ONE = True
ENABLE_PRICE_LIMIT_CHECK = True
ENABLE_SUSPENSION_CHECK = True
MAX_LIQUIDITY_LOCK_DAYS = 10
LIQUIDITY_LOCK_REPORT_CSV = RESULT_DIR / "extreme_liquidity_lock_report.csv"
ORDER_LEDGER_PREFIX = "backtest_orders"
BACKTEST_SUMMARY_V2_CSV = RESULT_DIR / "backtest_strategy_summary_v2.csv"
STRATEGY_RANK_SHIFT_REPORT_CSV = RESULT_DIR / "strategy_rank_shift_report.csv"
FORMAL_ADMISSION_REPORT_CSV = REPORT_DIR / "formal_admission_report.csv"
FORMAL_MANIFEST_JSON = REPORT_DIR / "formal_reproducibility_manifest.json"
FEATURE_LINEAGE_CSV = REPORT_DIR / "feature_lineage_report.csv"
FEATURE_TIMESTAMP_AUDIT_CSV = REPORT_DIR / "feature_timestamp_audit.csv"
BENCHMARK_REPORT_CSV = RESULT_DIR / "investable_benchmark_report.csv"
TAX_LEDGER_PREFIX = "backtest_tax_ledger"
CASH_LEDGER_PREFIX = "backtest_cash_ledger"
VALUATION_LEDGER_PREFIX = "backtest_valuation_ledger"
CORPORATE_ACTION_LEDGER_CSV = REPORT_DIR / "corporate_action_ledger.csv"
ADJUSTMENT_PTI_QUALITY_CSV = REPORT_DIR / "adjustment_pti_quality_report.csv"

EXECUTION_MODEL_VERSION = "tdx_daily_t_plus_1_nominal_v2"
SIGNAL_TIME_RULE = "t_close_after_market"
ORDER_TIME_RULE = "t_plus_1_open_preferred_daily_proxy"
EXECUTION_PRICE_RULE = "nominal_daily_price_only"
EXECUTION_FEASIBILITY_RULE = "suspension_and_price_limit_and_cash_budget"
FALLBACK_PRICE_RULE = "daily_nominal_close_proxy_disclosed"
DATA_RESOLUTION_REQUIRED = "daily"

TRANSFER_FEE_RATE = 0.00001
DIVIDEND_TAX_RATE = 0.20
TAX_POLICY_VERSION = "cn_a_share_conservative_v1"
DIVIDEND_TAX_ASSUMPTION = "Conservative uniform dividend tax rate; holding-period tax is not modeled."
TAX_MODEL_LIMITATIONS = "Dividend payment-date and holding-period tax require verified corporate-action ledgers."

SUSPENSION_FORMAL_BLOCK_AUM_RATIO = 0.05
LIMIT_DOWN_LIQUIDITY_DISCOUNT = 0.10
VALUATION_MODEL_VERSION = "conservative_liquidity_discount_v1"
VALUATION_ASSUMPTION = "Blocked positions are discounted conservatively from nominal value."

RAW_DAILY_PARQUET = PROCESSED_DIR / "tdx_daily_raw.parquet"
CLEAN_DAILY_PARQUET = PROCESSED_DIR / "tdx_daily_clean.parquet"
FEATURE_DAILY_PARQUET = PROCESSED_DIR / "tdx_daily_features.parquet"

FAILED_CODES_CSV = REPORT_DIR / "failed_codes.csv"
STOCK_INFO_CSV = REPORT_DIR / "instrument_info.csv"
ABNORMAL_RETURN_CSV = REPORT_DIR / "abnormal_return_rows.csv"
DATA_QUALITY_SUMMARY_CSV = REPORT_DIR / "data_quality_summary.csv"

# Phase-one decision council. These settings are frozen for exploratory
# rules-based governance backtests and must be included in run manifests.
ENABLE_DECISION_COUNCIL = True
DECISION_COUNCIL_VERSION = "rules_based_president_v2_p0_p1_5"
SAFETY_PROXY_MODE = "strict"
SAFETY_PROXY_SYMBOLS = ("sh510300", "sh510310", "sz159919")
SAFETY_PROXY_MAX_LAG_DAYS = 1
SAFETY_PROXY_MAX_MISSING_DAYS = 2
SAFETY_WARNING_DRAWDOWN = 0.015
SAFETY_HIGH_DRAWDOWN = 0.03
SAFETY_CRISIS_DRAWDOWN = 0.05
SAFETY_WARNING_LIQUIDITY_STRESS = 0.20
SAFETY_HIGH_LIQUIDITY_STRESS = 0.35
SAFETY_CRISIS_LIQUIDITY_STRESS = 0.50
SAFETY_SELL_FLOW_ALERT_RATIO = 0.02
GOVERNANCE_PLAN_HORIZON_DAYS = 5
GOVERNANCE_MIN_HOLDING_DAYS = 5
GOVERNANCE_SINGLE_WEIGHT_DRIFT = 0.02
GOVERNANCE_TOTAL_WEIGHT_DRIFT = 0.10
GOVERNANCE_MAX_POSITION_WEIGHT = 0.20
GOVERNANCE_MAX_PROTOTYPE_SECTOR_WEIGHT = 0.40
GOVERNANCE_REALLOCATION_ITERATIONS = 5
GOVERNANCE_REALLOCATION_MIN_WEIGHT = 0.001
GOVERNANCE_VOLATILITY_CAP_MULTIPLIER = 1.20
GOVERNANCE_LOCK_HAIRCUT_DAYS = 5
GOVERNANCE_LOCK_ALERT_DAYS = 10
GOVERNANCE_LOCK_HAIRCUT_RATIO = 1.0
GOVERNANCE_REWARD_DRAWDOWN_BUDGET = 0.05
GOVERNANCE_REWARD_TURNOVER_PENALTY = 0.50
GOVERNANCE_REWARD_DRAWDOWN_PENALTY = 3.0
GOVERNANCE_REPUTATION_WARMUP_DAYS = 252
GOVERNANCE_REPUTATION_HALF_LIFE = 20
GOVERNANCE_REPUTATION_UPDATE_DAYS = 5
GOVERNANCE_REPUTATION_SENSITIVITY = 1.5
GOVERNANCE_REPUTATION_MIN_WEIGHT = 0.25
GOVERNANCE_REPUTATION_MAX_WEIGHT = 4.0
GOVERNANCE_REPUTATION_MAX_STEP_RATIO = 0.05
GOVERNANCE_TRAIN_PURGE_PERIODS = 20
GOVERNANCE_TRAIN_EMBARGO_PERIODS = 5
GOVERNANCE_ENVIRONMENT_MANIFEST_JSON = REPORT_DIR / "decision_council_environment_manifest.json"
GOVERNANCE_OUTPUT_DIR = RESULT_DIR / "decision_council"
GOVERNANCE_INITIAL_CASH = 1_000_000.0
GOVERNANCE_ALPHA_MODELS = ("momentum_20", "mom_lowvol", "ma_break")
GOVERNANCE_ALPHA_CANDIDATE_LIMIT = 200
GOVERNANCE_DEFAULT_TOP_N = 20
GOVERNANCE_ENTRY_RANK_LIMIT = 20
GOVERNANCE_HOLD_RANK_LIMIT = 100
GOVERNANCE_NORMAL_REBALANCE_INTERVAL_DAYS = 5
GOVERNANCE_DEFAULT_TURNOVER_BUDGET = 0.05
GOVERNANCE_WEEKLY_TURNOVER_BUDGET = 0.20
GOVERNANCE_PARTIAL_ADJUSTMENT_RATE = 0.25
GOVERNANCE_INITIAL_TRANSITION_DAYS = 20
GOVERNANCE_ALLOWED_INSTRUMENT_TYPES = ("stock", "etf_fund")
GOVERNANCE_MIN_DAILY_AMOUNT = 1_000_000.0
GOVERNANCE_STALE_PRICE_HAIRCUT_DAYS = 5
GOVERNANCE_STALE_PRICE_HAIRCUT_RATIO = 0.10
GOVERNANCE_IMPACT_MODEL_VERSION = "daily_sqrt_participation_proxy_v1_uncalibrated"
GOVERNANCE_IMPACT_SQRT_COEFFICIENT = 0.001
GOVERNANCE_IMPACT_MAX_RATE = 0.02
GOVERNANCE_MIN_DAILY_HISTORY = 20
GOVERNANCE_START_DATE = "2021-01-01"
GOVERNANCE_END_DATE = None
GOVERNANCE_PRELOAD_CALENDAR_DAYS = 60

# Position-management P0 contract defaults. These values define the first
# conservative Kelly implementation and are intentionally explicit because the
# decision matrix uses them as audited thresholds.
POSITION_KELLY_SCALE = 0.25
POSITION_MIN_ENTRY_KELLY_SCORE = 0.02
POSITION_HOLD_KELLY_SCORE = 0.03
POSITION_SEVERE_EXIT_KELLY_SCORE = 0.01
POSITION_MIN_P_WIN = 0.48
POSITION_EXIT_EXPECTED_RETURN_20D = -0.005
POSITION_EXIT_HYSTERESIS_DAYS = 3
POSITION_KELLY_DECLINE_DAYS = 5
POSITION_KELLY_DECLINE_RATIO = 0.50
POSITION_RISK_DISCOUNT_SMOOTH_DAYS = 5
POSITION_EMERGENCY_SINGLE_DAY_DRAWDOWN = 0.07
POSITION_A500_MIN_COVERAGE_RATIO = 0.80
POSITION_DEFAULT_RETURN_HORIZON_DAYS = 20

# P2-P7 industrial governance contracts. All stages run serially to keep
# memory bounded on a research workstation.
GOVERNANCE_INDUSTRIAL_DIR = RESULT_DIR / "decision_council_industrial"
GOVERNANCE_MODEL_REGISTRY_JSON = GOVERNANCE_INDUSTRIAL_DIR / "model_registry.json"
GOVERNANCE_INDUSTRIAL_MANIFEST_JSON = GOVERNANCE_INDUSTRIAL_DIR / "industrial_manifest.json"
GOVERNANCE_PHASE_GATE_CSV = GOVERNANCE_INDUSTRIAL_DIR / "phase_gate_report.csv"
GOVERNANCE_MODEL_CONGRESS_CSV = GOVERNANCE_INDUSTRIAL_DIR / "model_congress_catalog.csv"
GOVERNANCE_SAFETY_DAILY_CSV = GOVERNANCE_INDUSTRIAL_DIR / "safety_daily_dataset.csv"
GOVERNANCE_SAFETY_MODEL_JSON = GOVERNANCE_INDUSTRIAL_DIR / "safety_model.json"
GOVERNANCE_SAFETY_CALIBRATION_CSV = GOVERNANCE_INDUSTRIAL_DIR / "safety_calibration.csv"
GOVERNANCE_SAFETY_EVALUATION_CSV = GOVERNANCE_INDUSTRIAL_DIR / "safety_evaluation.csv"
GOVERNANCE_BANDIT_ACTIONS_CSV = GOVERNANCE_INDUSTRIAL_DIR / "bandit_action_contract.csv"
GOVERNANCE_MONITORING_POLICY_JSON = GOVERNANCE_INDUSTRIAL_DIR / "monitoring_rollback_policy.json"
GOVERNANCE_TRANSITION_PROTOCOL_JSON = GOVERNANCE_INDUSTRIAL_DIR / "initial_portfolio_transition_protocol.json"
GOVERNANCE_RESEARCH_REFERENCES_CSV = GOVERNANCE_INDUSTRIAL_DIR / "research_references.csv"
GOVERNANCE_STREAM_BATCH_SIZE = 50_000
GOVERNANCE_SAFETY_TRAIN_RATIO = 0.60
GOVERNANCE_SAFETY_VALIDATION_RATIO = 0.20
GOVERNANCE_SAFETY_MAX_ITERATIONS = 600
GOVERNANCE_SAFETY_LEARNING_RATE = 0.05
GOVERNANCE_SAFETY_L2 = 0.01
GOVERNANCE_MOMENTUM_REBOUND_DRAWDOWN = -0.08
GOVERNANCE_MOMENTUM_REBOUND_RETURN = 0.03
GOVERNANCE_BANDIT_ACTION_BOUND_RATIO = 0.20
GOVERNANCE_BANDIT_SHADOW_DAYS = 252
